### ISSUE TITLE
Seu site de demonstração não pode ser acessado/encontrado

### ISSUE THREAD

**Issue by alberto-rj** [hilanasilv/mulheres-na-tecnologia#1]
👋 Olá @hilanasilv!

👏 Parabéns por investir seu tempo e levar suas habilidades de front-end para o próximo nível ao construir esse projeto!

**Nota:** Você poderia resolver esse problema, baseando-se no [problema anterior que eu abri no seu outro repositório](https://github.com/hilanasilv/Responsividade/issues/1).

**Comment by hilanasilv** [comment]
Problema resolvido, obrigada pelo apoio! 🤝
